### ISSUE TITLE
Is this project still in progress?

### ISSUE THREAD

**Issue by agony09** [ChristopherDay/Gangster-Legends-V2#20]
Is this project still in progress or has it been terminated?

**Comment by ChristopherDay** [comment]
This is still in-progress, there have only been a few small updates over the last month as ive not had the time to work on it.

**Comment by agony09** [comment]
okay, thank you very much. i am testing your demo Server. is very nice, i like it.
but i am dont understand: 
i will buy a "9MM Beretta    $100 + 100" and i have 1200$ 
but the game says "You dont have enough to buy a 9MM Beretta"
100 + 100 = 200, or not ? or i am understand some wrong ?
(sorry for my bad english)

**Comment by ChristopherDay** [comment]
This is because within `ACP > Modules & Themes > Theme Manager` the `Points Name` is not set. The labe should be $100 + 100 Points.

**Comment by agony09** [comment]
okay, but i am testing your gameserver: http://glscript.cdcoding.com/demo/

**Comment by ChristopherDay** [comment]
Ive updated the demo, ill also make it default to `Points`

**Comment by tblapl** [comment]
Hello. The game does not work on the local server. I've got php 5.6 / 7.1 mysql 4.8.5 the login / registration menu appears and after logging in or registering a new user, the page is spilling out. Deleting a session again fires the main page, but the problem is repeated after logging in. On another (online) server, everything works. Any ideas?

**Comment by ChristopherDay** [comment]
if you are using xampp edit `class/templateRender.php` and comment line 164 out like so `//ini_set('pcre.jit', false);`
