### ISSUE TITLE
Custom Language Files (Idea)

### ISSUE THREAD

**Issue by tyupika93** [ChristopherDay/Gangster-Legends-V2#5]
I find it a good idea to invite separate language files to invite texts.

for example

```
<TH> NAME </ th>
<th style = "width: 100px"> Injury </ th>
<th style = "width: 100px"> Value </ th>
<th style = "width: 150px"> Location </ th>
<th style = "width: 160px"> Links </ th>
```

instead of

```
$ langfile = array (
"NAME" => "Here is the text", // "sample");
"iNJURY" => "Here is the text", // "sample");
"VALUE" => "Here is the text", // "sample");
```

and say there would be a language folder where there would be a garage.php file whose content

```
define ("NAME", "Name");
define ("INJURY", "Injury");
define ("VALUE", "Value");

?>
```

From the language file you have been called to get the garage php file for all the text.

**Comment by ChristopherDay** [comment]
This is planned, I have yet to find an easy to implement solution to this. I need to find the time to go back and convert any strings to translation files.

**Comment by W1-PopelierE** [comment]
https://github.com/Philipp15b/php-i18n

**Comment by uaktags** [comment]
Started working on i18n support, chose to go without the composer package as a number of things had to be changed.
If you like it, d340877 starts to show that we can have languages in a few places: ```./locale/{LANGUAGE}/translation.json``` is for the base install. 
Then .```/modules/installed/<module>/locale/{LANGUAGE}/translation.json``` is for each module to provide a translation.json set.
Right now I don't have anyway to block or deal with overloads, but by design in this Proof of Concept, each module would just create a new key within 
```
{
"modules":{
   "module_name_1": { "term": "This is a term for module_name_1"}
  }
}
```
so each module would just append to the "modules" key and shouldn't ever affect each other. If you like this, i'll continue down this path, create a PR and push it out.

**Comment by uaktags** [comment]
module.json needs to be abandoned for textual things like menus if you want language files. Currently looking into a workaround solution.

**Comment by uaktags** [comment]
Think I solved this by following the idea laid out in loggedin.hooks.php, if the modules use hooks to provide the "info" array, then we can use PHP functions against the text and get back to supporting multiple languages.
